name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build anb Push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      # - run: npm run test

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t victormatttosow/conta-justa:${{ steps.generate_tag.outputs.sha }} .

      - name: Push image
        run: docker push -t victormatttosow/conta-justa:${{ steps.generate_tag.outputs.sha }} .
